# Generated by Django 3.2 on 2021-04-13 02:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Middle_Initial', models.CharField(max_length=3)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=12, region=None)),
                ('Comment', models.TextField(default='', max_length=255)),
                ('Sub_Date', models.DateTimeField(default='', verbose_name='Date Submitted')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
