# Generated by Django 3.2 on 2021-04-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='slug',
        ),
        migrations.AddField(
            model_name='client',
            name='Service',
            field=models.SlugField(default='', max_length=25, unique=True),
        ),
    ]
