# Generated by Django 3.2 on 2021-04-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20210412_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.SlugField(default='', max_length=25, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='Service',
        ),
    ]
